=head1 SHCrossPowerSpectrum

=over 23

=item SHCrossPowerSpectrum -  

Compute the cross-power spectrum of two real functions.

=back

=head1 SYNOPSIS

=over 34

=item SUBROUTINE SHCrossPowerSpectrum ( 

C1, C2, LMAX, CSPECTRUM )

=back

=over 4

=over 10

=item REAL*8	

C1(2, LMAX+1, LMAX+1), C2(2, LMAX+1, LMAX+1), CSPECTRUM(LMAX+1)

=item INTEGER

LMAX

=back

=back

=head1 DESCRIPTION

I<SHCrossPowerSpectrum> will calculate the cross-power spectrum of two functions expressed in real spherical harmonics. For a given degree L, this is explicitly calculated as:

Sum_{i=1}^2 Sum_{m=0}^L C1(i, L+1, m+1) * C2(i, L+1, m+1) .

=head1 ARGUMENTS

=over 10

=item C1

(input) REAL*8, DIMENSION (2, LMAX+1, LMAX+1)

The first function expressed in real spherical harmonics.

=item C2

(input) REAL*8, DIMENSION (2, LMAX+1, LMAX+1)

The second function expressed in real spherical harmonics.
	
=item LMAX

(input) INTEGER

The maximum spherical harmonic degree for which the cross power spectrum will be calculated.

=item CSPECTRUM

(output) REAL*8, DIMENSION (LMAX+1)

The cross-power spectrum of the two functions.

=back

=head1 SEE ALSO

shpowerl(1), shpowerdensityl(1), shcrosspower(1), shcrosspowerdensityl(1), shpowerspectrum(1), shpowerspectrumdensity(1), shcrosspowerspectrumdensity(1), shadmitcorr(1)

L<http://shtools.ipgp.fr/>


=head1 COPYRIGHT AND LICENSE

Copyright 2012 by Mark Wieczorek <wieczor@ipgp.fr>.

This is free software; you can distribute and modify it under the terms of the revised BSD license.