.TH "pyeigvalsym" "1" "2015\-04\-28" "Python" "SHTOOLS 3.1"
.SH EigValSym
.PP
Compute the eigenvalues of a real symmetric matrix.
.SH Usage
.PP
\f[C]eval\f[] = pyshtools.EigValSym (\f[C]ain\f[], [\f[C]n\f[],
\f[C]ul\f[]])
.SH Returns
.TP
.B \f[C]eval\f[] : float, dimension (\f[C]n\f[])
The eigenvalues of \f[C]ain\f[], sorted from largest to smallest.
.RS
.RE
.SH Parameters
.TP
.B \f[C]ain\f[] : float, dimension (\f[C]nin\f[], \f[C]nin\f[])
The input real symmetric matrix.
By default, only the upper portion of the matrix is used.
.RS
.RE
.TP
.B \f[C]n\f[] : optional, integer, default = \f[C]nin\f[]
The rank of the matrix \f[C]ain\f[].
.RS
.RE
.TP
.B \f[C]ul\f[] : optional, character, default = \f[C]U\f[]
If \f[C]U\f[] then the upper portion of the matrix \f[C]ain\f[] will be
used (default).
If \f[C]L\f[] then the lower portion of the matrix \f[C]ain\f[] will be
used.
.RS
.RE
.SH Description
.PP
\f[C]EigValSym\f[] will calculate the eigenvalues of a real symmetric
matrix.
By default, only the upper portion of the matrix is used, but this can
be changed by the optional argument \f[C]ul\f[].
The eigenvalues are sorted from largest to smallest.
The matrix \f[C]ain\f[] is first factorized into a tridiagonal matrix
using the LAPACK routine \f[C]DSYTRD\f[], and then the eigenvalues are
calculated by a call to \f[C]DSTEGR\f[].
.SH See also
.PP
eigvalvecsym, eigvalvecsymtri
