.TH "pyshcrosspowerspectrum" "1" "2015\-04\-06" "Python" "SHTOOLS 3.1"
.SH SHCrossPowerSpectrum
.PP
Compute the cross\-power spectrum of two real functions.
.SH Usage
.PP
\f[C]cspectrum\f[] = pyshtools.SHCrossPowerSpectrum (\f[C]cilm1\f[],
\f[C]cilm2\f[], [\f[C]lmax\f[]])
.SH Returns
.TP
.B \f[C]cspectrum\f[] : float, dimension (\f[C]lmax\f[]+1)
The cross\-power spectrum of the two functions.
.RS
.RE
.SH Parameters
.TP
.B \f[C]cilm1\f[] : float, dimension (2, \f[C]lmaxin1\f[]+1, \f[C]lmaxin1\f[]+1)
The first function expressed in real spherical harmonics.
.RS
.RE
.TP
.B \f[C]cilm2\f[] : float, dimension (2, \f[C]lmaxin2\f[]+1, \f[C]lmaxin2\f[]+1)
The second function expressed in real spherical harmonics.
.RS
.RE
.TP
.B \f[C]lmax\f[] : optional, integer, default = min(\f[C]lmaxin1\f[], \f[C]lmaxin2\f[])
The maximum spherical harmonic degree to calculate the cross\-power
spectrum.
This must be less than or equal to the minimum of \f[C]lmaxin1\f[] and
\f[C]lmaxin2\f[].
.RS
.RE
.SH Description
.PP
\f[C]SHCrossPowerSpectrum\f[] will calculate the cross\-power spectrum
of two real functions expressed in real spherical harmonics.
For a given degree spherical harmonic degree \f[C]l\f[], this is
explicitly calculated as:
.PP
\f[C]cspectrum(l)\ =\ Sum_{i=0}^1\ Sum_{m=0}^l\ cilm1[i,\ l,\ m]\ *\ cilm2[i,\ l,\ m]\f[].
.SH See also
.PP
shpowerl, shpowerdensityl, shcrosspower, shcrosspowerdensityl,
shpowerspectrum, shpowerspectrumdensity, shcrosspowerspectrumdensity,
shadmitcorr
