.TH "shcilmtocindex" "1" "2015\-04\-02" "SHTOOLS 3.0" "SHTOOLS 3.0"
.SH SHCilmToCindex
.PP
Convert a three\-dimensional array of spherical harmonic coefficients to
a two\-dimensional indexed array.
.SH Usage
.PP
call SHCilmToCindex (\f[C]cilm\f[], \f[C]cindex\f[], \f[C]degmax\f[])
.SH Parameters
.TP
.B \f[C]cilm\f[] : input, real*8, dimension (2, :, :)
The input spherical harmonic coefficients.
\f[C]cilm(1,:,:)\f[] and \f[C]cilm(2,:,:)\f[] correspond to either the
real and imaginary components, or cosine and sine coefficients,
respectively.
.RS
.RE
.TP
.B \f[C]cindex\f[] : output, real*8, dimension (2, :)
The indexed output spherical harmonic coefficients.
The second dimension of this array must be greater than
\f[C](lmax+1)*(lmax+2)/2\f[] where \f[C]lmax\f[] is the maximum degree
of \f[C]cilm\f[].
.RS
.RE
.TP
.B \f[C]degmax\f[] : input, integer, optional
The maximum degree of the output coefficients.
By default, the entire array \f[C]cilm\f[] will be converted.
.RS
.RE
.SH Description
.PP
\f[C]SHCilmToCindex\f[] will convert a three\-dimensional array of
spherical harmonic coefficients to a two\-dimensional indexed array.
The degree \f[C]l\f[] and order \f[C]m\f[] corresponds to the index
\f[C]l*(l+1)/2+m+1\f[].
The default is to convert the entire array \f[C]cilm\f[], but a subset
of this array can be converted by specifying the optional argument
\f[C]degmax\f[].
.SH See also
.PP
shcindextocilm, shcindextovector, shvectortocilm
