source "https://rubygems.org"

# to publish on github page
gem 'github-pages', group: :jekyll_plugins
#gem 'jekyll_version_plugin', group: :jekyll_plugins

# to publish without github page
#gem "jekyll"
gem "webrick", "~> 1.8"
