=head1 PlBar

=over 8

=item PlBar -  

Compute all the geodesy-normalized Legendre polynomials.

=back

=head1 SYNOPSIS

=over 19

=item SUBROUTINE PlBar ( 

P, LMAX, Z )

=back

=over 4

=over 10

=item REAL*8	

P(LMAX+1), Z

=item INTEGER

LMAX

=back

=back

=head1 DESCRIPTION

I<PlBar> will calculate all of the geodesy-normalized Legendre polynomials up to degree LMAX for a given argument. These are calculated using a standard three-term recursion formula. The integral of the geodesy-normalized Legendre polynomials over the interval [-1, 1] is 2.

=head1 ARGUMENTS

=over 10

=item P

(output) REAL*8, DIMENSION (LMAX+1)

An array of geodesy-normalized Legendre polynomials up to degree LMAX. Degree L corresponds to array index L+1.
	
=item LMAX

(input) INTEGER

The maximum degree of the Legendre polynomials to be computed.

=item Z

(input) REAL*8

The argument of the Legendre polynomial.

=back

=head1 SEE ALSO

plbar_d1(1), plmbar(1), plmbar_d1(1), plon(1), plon_d1(1), plmon(1), plmon_d1(1), plschmidt(1), plschmidt_d1(1), plmschmidt(1), plmschmidt_d1(1), plegendre(1), plegendre_d1(1), plegendrea(1), plegendrea_d1(1)

L<http://shtools.ipgp.fr/>

=head1 COPYRIGHT AND LICENSE

Copyright 2012 by Mark Wieczorek <wieczor@ipgp.fr>.

This is free software; you can distribute and modify it under the terms of the revised BSD license.