=head1 SHCrossPowerDensityLC

=over 24

=item SHCrossPowerDensityLC -  

Compute the spectral cross-power density of two complex functions for a single degree L.

=back

=head1 SYNOPSIS

=over 44

=item COMPLEX*16 FUNCTION SHCrossPowerDensityLC (

C1, C2, L )

=back

=over 4

=over 14

=item COMPLEX*16	

C1(2, L+1, L+1), C2(2, L+1, L+1)

=item INTEGER

L

=back

=back

=head1 DESCRIPTION

I<SHCrossPowerDensityLC> will calculate the spectral cross-power density of two functions expressed in complex spherical harmonics for a single degree L. This is explicitly calculated as:

Sum_{i=1}^2 Sum_{m=0}^L C1(i, L+1, m+1) * conjg[C2(i, L+1, m+1)] / (2L + 1).

=head1 ARGUMENTS

=over 10

=item C1

(input) COMPLEX*16, DIMENSION (2, L+1, L+1)

The first function expressed in complex spherical harmonics.

=item C2

(input) COMPLEX*16, DIMENSION (2, L+1, L+1)

The second function expressed in complex spherical harmonics.
	
=item L

(input) INTEGER

The spherical harmonic degree for which the cross power density will be calculated.

=back

=head1 SEE ALSO

shpowerlc(1), shpowerdensitylc(1), shcrosspowerlc(1), shpowerspectrumc(1), shpowerspectrumdensityc(1), shcrosspowerspectrumc(1), shcrosspowerspectrumdensityc(1), shadmitcorr(1)

L<http://shtools.ipgp.fr/>


=head1 COPYRIGHT AND LICENSE

Copyright 2012 by Mark Wieczorek <wieczor@ipgp.fr>.

This is free software; you can distribute and modify it under the terms of the revised BSD license.