=head1 SHConfidence

SHConfidence -  Compute the probability that two sets of spherical harmonic coefficients are correlated at a given degree and for a given correlation coefficient.

=head1 SYNOPSIS

=over 31

=item REAL*8 FUNCTION SHConfidence ( 

L, CORR )

=back

=over 4

=over 10

=item INTEGER

L

=item REAL*8

CORR

=back

=back

=head1 DESCRIPTION

I<SHConfidence> will calculate the probability (between 0 and 1) that two sets of spherical harmonic coefficients are linearly correlated at a given degree and for a given correlation coefficient at that degree. This is calculated using equation A7 from Pauer et al. (2006).

=head1 ARGUMENTS

=over 10

=item L

(input) INTEGER

The spherical harmonic degree to consider.
	
=item CORR

(input) REAL*8

The correlation coefficient of the two data sets at degree L.
	

=back

=head1 SEE ALSO

shadmitcorr(1), shpowerspectrum(1), shcrosspowerspectrum(1)

L<http://shtools.ipgp.fr/>

=head1 REFERENCES

Pauer, M, K. Fleming, and O. Cadek, Modeling the dynamic component of the geoid and topography of Venus, J. Geophys. Res., 111, E11012, doi:10.1029/2005JE002511, 2006.

=head1 COPYRIGHT AND LICENSE

Copyright 2012 by Mark Wieczorek <wieczor@ipgp.fr>.

This is free software; you can distribute and modify it under the terms of the revised BSD license.