name: Build wheels

on:
  push:
  pull_request:
    branches: [master, develop]
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon.
        # os: [ubuntu-latest, macos-13, macos-14, [windows-latest]
        os: [ubuntu-latest, macos-13, macos-14]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 250
          fetch-tags: true

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.17.0
        env:
          CIBW_BEFORE_ALL_MACOS: brew reinstall gcc fftw lapack
          CIBW_BEFORE_ALL_LINUX: yum install -y fftw-devel openblas-devel
          CIBW_SKIP: "*-manylinux_i686 *-musllinux*"
          # CIBW_ARCHS_LINUX: "auto aarch64"

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
